### ISSUE TITLE
how to convert bs to ad? Is there any function?

### ISSUE THREAD

**Issue by paras205** [sandy100/react-nepali-datepicker#2]

**Comment by sandy100** [comment]
@paras205 I hope this helps you.

`import { BSToAD } from "bikram-sambat-js";`
and you can get AD date from bs date using `BSToAD(date);`

Note: Date must be in the format `YYYY-MM-DD`

**Comment by paras205** [comment]
Thank you for your email it helps but I have one more question what about
populating the field? we cannot send value from component

**Comment by sandy100** [comment]
@paras205 , Can you please explain a little bit more. I am not getting your point, what you want to do?

**Comment by paras205** [comment]
I want to update the value
![Screenshot_1](https://user-images.githubusercontent.com/34994355/79557594-8a44d900-80c2-11ea-852c-3e1405a26eae.png)
![Screenshot_1](https://user-images.githubusercontent.com/34994355/79557651-a5174d80-80c2-11ea-9e05-a1cd4d499d30.png)

**Comment by paras205** [comment]
I want date from 1970 to 1800

**Comment by sandy100** [comment]
Sorry, In this release, I have only added the date from 2000 to 2085 BS. You can not get dates before 2000 BS. I will add this in the next release.
